create table players(
    username varchar(255) primary key,
    email varchar(255) not null,
    password_hash varchar(255) not null
);

create table games(
    id auto_increment primary key,
    player1 varchar(255) not null,
    player2 varchar(255) not null,
    player3 varchar(255) not null,
    winner varchar(255) not null,
    winner_goal varchar(255) not null,

    foreign key(player1) references players(username),
    foreign key(player2) references players(username),
    foreign key(player3) references players(username),
    foreign key(winner) references players(username)
);

insert into players(username, email, password_hash) values
('cristian', 'cristian@email.com', '$2b$12$DZUa.I0rNkS6e.dCp.OnmeDODDk8No.2rkhn2lWU0s0JME4Ah/I6O'),
('gieri', 'gieri@email.com', '$2b$12$jrFPXMFZIPP4n3/L/N4glOW3/asgMLEcGxKZyC8YGAcgViVTAZrpK'),
('pietro', 'pietro@email.com', '$2b$12$n/5L4rJbKXj.DAJjgMONGOktzePquyRt/4Zx8KXD1LqqubFHhAuGO'),
('amin', 'amin@email.com', '$2b$12$kH5p0.IBI3WdKPqvX9JHS.cpgocDrAoT0/2KIHsAel7pvWmjtNCY2'),
('leonardo', 'leonardo@email.com', '$2b$12$kuhB4WrX5FTv.VEJ8Fe1i.FFsdKsjZxxMrkh/e5QDNAAaxZC6NDh2'),
('gabbo', 'gabbo@gmail.com', '$2b$12$Ah9Ke.rHg9aVVFzgf95N9unvb1MeOGocxNwXA5RdJG4AnofXd2CJS'),
('cri', 'cri@email.com', '$2b$12$IZwCHhXPHv8hbvnTDweW3OQ47kdqXgAsA/6vtg2WB11t1jl4G3oyK'),
('giuseppe', 'giuseppe@gmail.com', '$2b$12$k0TSE3MXbM7pkvG.6abyHeRWkIso1C1bLwb94hI3zi6Hww2MtXn6C'),
('federico', 'federico@gmail.com', '$2b$12$qUL1apy4Lq/twRt9moyOguqFH4Q9kwxR3C8maDtH/dVD9s1uEGLu2'),
('alberto', 'alberto@email.com', '$2b$12$Ule.f77PYLI/94FyQ3qQpuRfTjDU.lh51HT9xXFJgWeoMrFmMmwqC'),
('edoardo', 'edoardo@email.com', '$2b$12$Gl.qe5ZMxOZ/ivbQbA6hV.oFISJDspvwxl8VF/TYfYfnfPq8gFyEm'),
('giorgio', 'giorgio@email.com', '$2b$12$E0ttNngct8J4H7MTWYQt0O1IrkX8BVBwsNI3Fyq9XRwOJ3tnwUZfm'),
('emanuel', 'emanuel@email.com', '$2b$12$29BPrtSyOOAzC8233myOQuoZcADPrmsRWlZfoUjawUDShJWqUx.Aq'),
('letizia', 'letizia@email.com', '$2b$12$u72K1qqZQByaONROckTx6.Drcbzz3YPHh5TPB27.jxsrmxwSaMwKu'),
('francesca', 'francesca@email.com', '$2b$12$Gc1MyerdoX8oEGFuG1njf.WfNKSavrqNEaVq9SwodVGpNYUM.kYiG'),
('ermenegildo', 'ermenegildo@email.com', '$2b$12$8mYWdTF2d04/YFtN0P8e6.oYpJ5rRvwyINJpSQB3cf3ZoKIG35fZa'),
('gianfranco', 'gianfranco@email.com', '$2b$12$jfvCNNd/d8SmjYqZmmNgA.YzYJ.iilo61geFegba.KCtaIYmcGcBq'),
('maria', 'maria@email.com', '$2b$12$0Ban.pNYZjzcB5Zhn7o/2.3htU.qSlr13qWx3pmhkKGlyD1/RAG/u'),
('mario', 'mario@email.com', '$2b$12$ntONnCr4tGTlwsK5PlB4l.VtJTCQQDLX8yz7g3kbLQ.xEWQGfdKna'),
('luigi', 'luigi@email.com', '$2b$12$NCfvMbIHaBVSEfecMPbxi.XQquLzEpwtCUiH6jSF6tOJzNxkNy8Ye');

insert into games(id,player1, player2, player3, winner, winner_goal) values
(1, 'cristian', 'gieri', 'pietro', 'cristian', 'asia'),
(2, 'amin', 'leonardo', 'gabbo', 'leonardo', 'africa'),
(3, 'cri', 'giuseppe', 'federico', 'giuseppe', 'europe'),
(4, 'alberto', 'edoardo', 'giorgio', 'edoardo', 'north america'),
(5, 'emanuel', 'letizia', 'francesca', 'letizia', 'south america'),
(6, 'ermenegildo', 'gianfranco', 'maria', 'gianfranco', 'australia'),
(7, 'mario', 'luigi', 'cristian', 'mario', 'antarctica'),
(8, 'gieri', 'pietro', 'amin', 'amin', 'asia'),
(9, 'leonardo', 'gabbo', 'cri', 'cri', 'africa'),
(10, 'giuseppe', 'federico', 'alberto', 'federico', 'europe'),
(11, 'edoardo', 'giorgio', 'emanuel', 'giorgio', 'north america'),
(12, 'letizia', 'francesca', 'ermenegildo', 'francesca', 'south america'),
(13, 'gianfranco', 'maria', 'mario', 'maria', 'australia'),
(14, 'luigi', 'cristian', 'gieri', 'luigi', 'antarctica'),
(15, 'pietro', 'amin', 'leonardo', 'pietro', 'asia'),
(16, 'gabbo', 'cri', 'giuseppe', 'gabbo', 'africa'),
(17, 'federico', 'alberto', 'edoardo', 'alberto', 'europe'),
(18, 'giorgio', 'emanuel', 'letizia', 'emanuel', 'north america'),
(19, 'francesca', 'ermenegildo', 'gianfranco', 'ermenegildo', 'south america'),
(20, 'maria', 'mario', 'luigi', 'mario', 'australia'),
(21, 'cristian', 'gieri', 'pietro', 'cristian', 'antarctica'),
(22, 'amin', 'leonardo', 'gabbo', 'amin', 'asia'),
(23, 'cri', 'giuseppe', 'federico', 'giuseppe', 'africa'),
(24, 'alberto', 'edoardo', 'giorgio', 'giorgio', 'europe'),
(25, 'emanuel', 'letizia', 'francesca', 'emanuel', 'north america'),
(26, 'ermenegildo', 'gianfranco', 'maria', 'gianfranco', 'south america'),
(27, 'mario', 'luigi', 'cristian', 'mario', 'australia'),
(28, 'gieri', 'pietro', 'amin', 'gieri', 'antarctica'),
(29, 'leonardo', 'gabbo', 'cri', 'gabbo', 'asia'),
(30, 'giuseppe', 'federico', 'alberto', 'giuseppe', 'africa'),
(31, 'edoardo', 'giorgio', 'emanuel', 'giorgio', 'europe'),
(32, 'letizia', 'francesca', 'ermenegildo', 'letizia', 'north america'),
(33, 'gianfranco', 'maria', 'mario', 'mario', 'south america'),
(34, 'luigi', 'cristian', 'gieri', 'luigi', 'australia'),
(35, 'pietro', 'amin', 'leonardo', 'pietro', 'antarctica'),
(36, 'gabbo', 'cri', 'giuseppe', 'gabbo', 'asia'),
(37, 'federico', 'alberto', 'edoardo', 'federico', 'africa'),
(38, 'giorgio', 'emanuel', 'letizia', 'giorgio', 'europe'),
(39, 'francesca', 'ermenegildo', 'gianfranco', 'gianfranco', 'north america'),
(40, 'maria', 'mario', 'luigi', 'mario', 'south america'),
(41, 'cristian', 'gieri', 'pietro', 'cristian', 'australia'),
(42, 'amin', 'leonardo', 'gabbo', 'amin', 'antarctica'),
(43, 'cri', 'giuseppe', 'federico', 'giuseppe', 'asia'),
(44, 'cristian', 'amin', 'cri', 'amin', 'antarctica'),
(45, 'gieri', 'leonardo', 'giuseppe', 'leonardo', 'asia'),
(46, 'pietro', 'gabbo', 'alberto', 'gabbo', 'africa'),
(47, 'amin', 'cri', 'edoardo', 'cri', 'europe'),
(48, 'leonardo', 'giuseppe', 'giorgio', 'giuseppe', 'north america'),
(49, 'gabbo', 'alberto', 'emanuel', 'alberto', 'south america'),
(50, 'cri', 'edoardo', 'letizia', 'edoardo', 'australia'),
(51, 'giuseppe', 'giorgio', 'ermenegildo', 'giorgio', 'antarctica'),
(52, 'alberto', 'emanuel', 'gianfranco', 'emanuel', 'asia'),
(53, 'edoardo', 'letizia', 'maria', 'letizia', 'africa'),
(54, 'giorgio', 'ermenegildo', 'mario', 'ermenegildo', 'europe'),
(55, 'emanuel', 'gianfranco', 'luigi', 'gianfranco', 'north america'),
(56, 'letizia', 'maria', 'cristian', 'maria', 'south america'),
(57, 'ermenegildo', 'mario', 'gieri', 'mario', 'australia'),
(58, 'gianfranco', 'luigi', 'pietro', 'luigi', 'antarctica'),
(59, 'maria', 'cristian', 'amin', 'cristian', 'asia'),
(60, 'mario', 'gieri', 'leonardo', 'gieri', 'africa'),
(61, 'luigi', 'pietro', 'gabbo', 'pietro', 'europe'),
(62, 'cristian', 'amin', 'cri', 'amin', 'north america'),
(63, 'gieri', 'leonardo', 'giuseppe', 'leonardo', 'south america'),
(64, 'pietro', 'gabbo', 'alberto', 'gabbo', 'australia'),
(65, 'amin', 'cri', 'edoardo', 'cri', 'antarctica'),
(66, 'leonardo', 'giuseppe', 'giorgio', 'giuseppe', 'asia'),
(67, 'gabbo', 'alberto', 'emanuel', 'alberto', 'africa'),
(68, 'cri', 'edoardo', 'letizia', 'edoardo', 'europe'),
(69, 'giuseppe', 'giorgio', 'ermenegildo', 'giorgio', 'north america'),
(70, 'alberto', 'emanuel', 'gianfranco', 'emanuel', 'south america'),
(71, 'edoardo', 'letizia', 'maria', 'letizia', 'australia'),
(72, 'giorgio', 'ermenegildo', 'mario', 'ermenegildo', 'antarctica'),
(73, 'emanuel', 'gianfranco', 'luigi', 'gianfranco', 'asia'),
(74, 'letizia', 'maria', 'cristian', 'maria', 'africa'),
(75, 'ermenegildo', 'mario', 'gieri', 'mario', 'europe'),
(76, 'gianfranco', 'luigi', 'pietro', 'luigi', 'north america'),
(77, 'maria', 'cristian', 'amin', 'cristian', 'south america'),
(78, 'mario', 'gieri', 'leonardo', 'gieri', 'australia'),
(79, 'luigi', 'pietro', 'gabbo', 'pietro', 'antarctica'),
(80, 'cristian', 'amin', 'cri', 'amin', 'asia'),
(81, 'gieri', 'leonardo', 'giuseppe', 'leonardo', 'africa'),
(82, 'pietro', 'gabbo', 'alberto', 'gabbo', 'europe'),
(83, 'amin', 'cri', 'edoardo', 'cri', 'north america'),
(84, 'leonardo', 'giuseppe', 'giorgio', 'giuseppe', 'south america'),
(85, 'giorgio', 'cristian', 'amin', 'cristian', 'north america');